# Resources for testing the ext2 fs functionality
sysres-y += small.txt@/test/systemimg/
sysres-y += medium.txt@/test/systemimg/
sysres-y += big.txt@/test/systemimg/
sysres-y += huge.txt@/test/systemimg/

datares-y += readme@/test/
