# Resources for testing the ext2 fs functionality
resource-y += small.txt@/test/systemimg/
resource-y += medium.txt@/test/systemimg/
resource-y += big.txt@/test/systemimg/
resource-y += huge.txt@/test/systemimg/
