obj-$(CONFIG_CPU_32_BITS) += syscall32.o
obj-$(CONFIG_CPU_64_BITS) += syscall64.o

# System call objects
obj-$(CONFIG_SYSCALL_OPEN_BACKDOOR) += backdoor.o
obj-y += sched.o
obj-y += io.o
obj-y += time.o
obj-y += process.o
obj-y += dir.o
obj-y += file.o
obj-y += property.o