obj-$(CONFIG_CPU_32_BITS) += syscall32.o
obj-$(CONFIG_CPU_64_BITS) += syscall64.o

# System call objects
obj-$(CONFIG_SYSCALL_OPEN_BACKDOOR) += backdoor.o
obj-y += exit.o
obj-y += yield.o
obj-y += puts.o
obj-y += getpid.o
obj-y += time.o
obj-y += sleep.o
obj-y += priority.o
obj-y += procname.o
obj-y += readline.o
obj-y += getc.o
obj-y += dir.o
obj-y += file.o